### ISSUE TITLE
Python 3.4 not supported?

### ISSUE THREAD

**Issue by jacquerie** [david-caro/python-autosemver#47]
Hey @david-caro! o/

It seems that Python 3.4 is not supported. Here's what I get when I try to install `python-autosemver` on that Python version: https://travis-ci.org/jacquerie/flask-shell-bpython/jobs/300701330#L508. Any idea why?

**Comment by david-caro** [comment]
It turns out that 3.4 handles dictionary `keys`, `items` and `values` in a non-backwards compatible way, specifically for the `reversed` function, so I had to add some ugly trick just in that case. 0.5.3 should fix it, can you retry and close if so?

**Comment by jacquerie** [comment]
Sounds like you fixed it: https://travis-ci.org/jacquerie/flask-shell-bpython/builds/300897768

Thanks!
