### ISSUE TITLE
Broken Python 3.5 compatibility

### ISSUE THREAD

**Issue by elWanderero** [david-caro/python-autosemver#52]
Commit 401399120a14919ab80 breaks compatibility with Python 3.5 and earlier, by using Python 3.6 inline type annotations. I.e.
```python
WITH_GIT: bool = True
```
instead of
```python
WITH_GIT = True # type: bool
```

I guess this is intentional, since [travis.yml](https://github.com/david-caro/python-autosemver/blob/3b7eb2f4b12160614152b9212b4ef297b759c3a7/.travis.yml) only mentions Python 3.6-3.9?

**Comment by elWanderero** [comment]
https://autosemver.readthedocs.io/en/latest/contributing.html#pull-request-guidelines mentions Python 2.7 and 3.5, but that is obviously no longer accurate.

**Comment by david-caro** [comment]
I totally missed this, yes, thanks! Merged your PR.
